// Maintainer helper: refresh the offline editor's sample data and shared style.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname,'..');
const read = name => fs.readFileSync(path.join(root,name),'utf8');
const site = JSON.parse(read('content/site.json'));
// The portable editor has no server requirement or external image dependency.
if (site.profileImage && !/^https?:\/\//.test(site.profileImage)) site.profileImage = '';
const data = {version:1,site,posts:JSON.parse(read('content/posts.json')).posts,projects:JSON.parse(read('content/projects.json')).projects,notes:JSON.parse(read('content/notes.json')).notes};
fs.writeFileSync(path.join(root,'editor/seed.js'),`// Generated by tools/prepare-editor.cjs.\nwindow.PORTFOLIO_SEED = ${JSON.stringify({data,css:read('assets/css/style.css')})};\n`);
console.log('Offline editor sample content and styles refreshed.');
